proyecto/colaborador/urls.py
from django.urls import path

from colaborador.views import (
    ColaboradorCreate,
    ColaboradorDelete,
    ColaboradorDetail,
    ColaboradorList,
    ColaboradorUpdate,
    ImagenCreate,
    ImagenDelete,
    ImagenDetail,
    ImagenList,
    ImagenUpdate,
)

app_name = "colaborador"

urlpatterns = [
    path("colaborador/list", ColaboradorList.as_view(), name="colaborador_list"),
    path("colaborador/create", ColaboradorCreate.as_view(), name="colaborador_create"),
    path("colaborador/detail/<int:pk>", ColaboradorDetail.as_view(), name="colaborador_detail"),
    path("colaborador/update/<int:pk>", ColaboradorUpdate.as_view(), name="colaborador_update"),
    path("colaborador/delete/<int:pk>", ColaboradorDelete.as_view(), name="colaborador_delete"),
]

urlpatterns += [
    path("imagen/list", ImagenList.as_view(), name="imagen_list"),
    path("imagen/create", ImagenCreate.as_view(), name="imagen_create"),
    path("imagen/detail/<int:pk>", ImagenDetail.as_view(), name="imagen_detail"),
    path("imagen/update/<int:pk>", ImagenUpdate.as_view(), name="imagen_update"),
    path("imagen/delete/<int:pk>", ImagenDelete.as_view(), name="imagen_delete"),
]

proyecto/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("colaboradores/", include("colaborador.urls")),
]

proyecto/home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from home.views import CustomLoginView, about, home_index, register

app_name = "home"

urlpatterns = [
    path("", home_index, name="index"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="home/logout.html"), name="logout"),
    path("register/", register, name="register"),
    path("about/", about, name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/colaborador/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
from django.utils import timezone


class Colaborador(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Colaborador", unique=True)
    edad = models.PositiveIntegerField()
    GENEROS = [("Mujer", "M"), ("Hombre", "H"), ("NoBinario", "NB")]
    genero = models.CharField(max_length=100, choices=GENEROS, default="Hombre")
    foto_perfil = models.ImageField(upload_to="fotos_perfil", null=True, blank=True)
    biografia = models.TextField(blank=False, null=False)
    fecha_registro = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        verbose_name = "Colaborador"
        verbose_name_plural = "Colaboradores"

    def __str__(self):
        return f"{self.usuario.username}."

    def clean(self):
        if self.edad < 18:
            raise ValidationError("Usted no puede ser menor de 18 años")


class Imagen(models.Model):
    colaborador = models.ForeignKey(Colaborador, on_delete=models.SET_NULL, null=True, blank=True)
    imagen = models.ImageField(upload_to="imagenes", null=True, blank=True)
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField(blank=False, null=False)
    fecha_subida = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        ordering = ("fecha_subida",)
        verbose_name = "Imagen"
        verbose_name_plural = "Imagenes"

    def __str__(self):
        return f"{self.titulo}, by {self.colaborador}"

proyecto/home/models.py
from django.db import models

# Create your models here.

proyecto/colaborador/forms.py
from django import forms

from . import models


class ColaboradorForm(forms.ModelForm):
    class Meta:
        model = models.Colaborador
        fields = "__all__"
        localized_fields = ("foto_perfil",)


class ImagenForm(forms.ModelForm):
    class Meta:
        model = models.Imagen
        fields = "__all__"

proyecto/home/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthentificationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

proyecto/colaborador/views.py
from typing import Any

from django.db.models import Q
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from colaborador.forms import ColaboradorForm, ImagenForm
from colaborador.models import Colaborador, Imagen

####### COLABORADOR #######


class ColaboradorList(ListView):
    model = Colaborador
    template_name = "colaborador/colaborador_list.html"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = Colaborador.objects.filter(Q(nombre__icontains=busqueda))
        return queryset


class ColaboradorCreate(CreateView):
    model = Colaborador
    form_class = ColaboradorForm
    success_url = reverse_lazy("colaborador:colaborador_list")
    template_name = "colaborador/colaborador_form.html"


class ColaboradorDetail(DetailView):
    model = Colaborador
    template_name = "colaborador/colaborador_detail.html"


class ColaboradorUpdate(UpdateView):
    model = Colaborador
    form_class = ColaboradorForm
    success_url = reverse_lazy("colaborador:colaborador_list")
    template_name = "colaborador/colaborador_form.html"


class ColaboradorDelete(DeleteView):
    model = Colaborador
    success_url = reverse_lazy("colaborador:colaborador_list")
    template_name = "colaborador/colaborador_delete.html"


####### IMAGEN #######


class ImagenList(ListView):
    model = Imagen
    template_name = "colaborador/imagen_list.html"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = Imagen.objects.filter(Q(nombre__icontains=busqueda))
        return queryset


class ImagenCreate(CreateView):
    model = Imagen
    form_class = ImagenForm
    success_url = reverse_lazy("colaborador:imagen_list")
    template_name = "colaborador/imagen_form.html"


class ImagenDetail(DetailView):
    model = Imagen
    template_name = "colaborador/imagen_detail.html"


class ImagenUpdate(UpdateView):
    model = Imagen
    form_class = ImagenForm
    success_url = reverse_lazy("colaborador:imagen_list")
    template_name = "colaborador/imagen_form.html"


class ImagenDelete(DeleteView):
    model = Imagen
    success_url = reverse_lazy("colaborador:imagen_list")
    template_name = "colaborador/imagen_delete.html"

proyecto/home/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import CustomAuthentificationForm, CustomUserCreationForm


def home_index(request):
    return render(request, "home/index.html")
    # return reverse_lazy("home:index")


def about(request):
    return render(request, "home/about.html")
    # return reverse_lazy("home:index")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthentificationForm
    template_name = "home/login.html"


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "home/index.html", {"mensaje": f"Usuario '{username}' creado"})
        ...
    else:
        form = CustomUserCreationForm()
    return render(request, "home/register.html", {"form": form})

proyecto/colaborador/templates/colaborador/colaborador_delete.html
{% extends 'home/base.html' %}
{% block title %}
    Colaboradores: Eliminar usuario Colaborador
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Colaboradores</h1>
{% endblock body_title %}
{% block body_subtitle %}
    <h2 class="text-center">Eliminar Usuario Colaborador</h2>
{% endblock body_subtitle %}
{% block content %}
    <div class="container">
        <p class="fs-5 fst-italic">¿Confirma eliminar a "{{ object.usuario }}"?</p>
        <form method="post" class="mt-3">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </form>
        <a href="{% url 'colaborador:colaborador_list' %}"
           class="btn btn-secondary mt-2">Volver a Colaboradores</a>
    </div>
{% endblock content %}

proyecto/colaborador/templates/colaborador/colaborador_detail.html
{% extends 'home/base.html' %}
{% block title %}
    Colaboradores: {{ object.usuario }}
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Sobre {{ object.usuario }}</h1>
{% endblock body_title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <ul class="list-group">
                    <li class="list-group-item text-center">
                        <img src="{{ object.foto_perfil.url }}"
                             alt="Foto Perfil"
                             style="width: 200px;
                                    height: 200px">
                    </li>
                    <li class="list-group-item">
                        <h4>Edad: {{ object.edad }} años</h4>
                    </li>
                    <li class="list-group-item">
                        <h4>Sexo: {{ object.genero }}</h4>
                    </li>
                    <li class="list-group-item">
                        <h4>Biografía:</h4>
                        <p>{{ object.biografia }}</p>
                    </li>
                </ul>
            </div>
        </div>
        <div class="text-center mt-4">
            <a href="{% url 'colaborador:colaborador_list' %}"
               class="btn btn-secondary">Volver</a>
            <a href="{% url 'home:index' %}" class="btn btn-primary ml-3">Ir a Inicio</a>
        </div>
    </div>
{% endblock content %}

proyecto/colaborador/templates/colaborador/colaborador_form.html
{% extends 'home/base.html' %}
{% block title %}
    {% if form.instance.pk %}
        Colaboradores: Editar {{ object.usuario }}
    {% else %}
        Colaboradores: Crear nuevo usuario
    {% endif %}
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Colaboradores</h1>
{% endblock body_title %}
{% block body_subtitle %}
    {% if form.instance.pk %}
        Modifique datos de {{ object.usuario }}
    {% else %}
        Crear un usuario colaborador nuevo
    {% endif %}
{% endblock body_subtitle %}
{% block content %}
    <div class="container">
        <form method="post" class="mt-4">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary">Confirmar</button>
        </form>
    </div>
{% endblock content %}

proyecto/colaborador/templates/colaborador/colaborador_list.html
{% extends 'home/base.html' %}
{% block title %}
    Colaboradores: Listado de Colaboradores
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Nuestros Colaboradores</h1>
{% endblock body_title %}
{% block body_subtitle %}
    <h2 class="text-center">Las personas que ayudan a que esta comunidad siga creciendo!</h2>
{% endblock body_subtitle %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for object in object_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ object.foto_perfil.url }}"
                             class="card-img-top"
                             alt="Foto Perfil"
                             style="height: 200px;
                                    object-fit: cover">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ object.usuario }}</h5>
                            <a href="{% url 'colaborador:colaborador_detail' object.id %}"
                               class="btn btn-primary mt-2">Ver detalles</a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'colaborador:colaborador_delete' object.id %}"
                                   class="btn btn-danger mt-2">Eliminar colaborador</a>
                                <a href="{% url 'colaborador:colaborador_update' object.id %}"
                                   class="btn btn-secondary mt-2">Modificar colaborador</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="text-center mt-4">
            <a href="{% url 'colaborador:colaborador_create' %}"
               class="btn btn-success">Crear nuevo colaborador</a>
            <a href="{% url 'home:index' %}" class="btn btn-secondary ml-3">Volver a Inicio</a>
        </div>
    </div>
{% endblock content %}

proyecto/colaborador/templates/colaborador/imagen_list.html
{% extends 'home/base.html' %}
{% block title %}
    Colaboradores: Galería
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Galería de Imágenes</h1>
{% endblock body_title %}
{% block body_subtitle %}
    <h2 class="text-center">Todo el material es libre de uso</h2>
{% endblock body_subtitle %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for object in object_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ object.imagen.url }}"
                             class="card-img-top"
                             alt="{{ object.titulo }}"
                             style="height: 200px;
                                    object-fit: cover">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.titulo }}</h5>
                            <p>
                                Posted by <a href="{% url 'colaborador:colaborador_detail' object.colaborador.id %}">{{ object.colaborador }}</a> {{ object.fecha_subida }}
                            </p>
                            <p>Descripción: {{ object.descripcion }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="text-center mt-4">
            <a href="{% url 'home:index' %}" class="btn btn-secondary">Volver a Inicio</a>
        </div>
    </div>
{% endblock content %}

proyecto/home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    Animalix | Acerca del desarrollador
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Sobre el desarrollador</h1>
{% endblock body_title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <p class="lead">¡Hola! Mi nombre es Luis Martin Castro, tengo 25 años y soy de Buenos Aires, Argentina.</p>
                <p>Este proyecto web fue desarrollado utilizando Python en Visual Studio Code junto con Django y Bootstrap 5.</p>
                <p>
                    Es mi primera experiencia en el desarrollo de una aplicación web de esta magnitud, y sé que aún tengo mucho por aprender (¡como un poco de HTML y JS!)
                </p>
                <p>
                    La idea principal del proyecto es crear un foro donde los usuarios puedan registrar sus datos y subir imágenes de animales para ser mostradas en una galería principal.
                </p>
                <p>
                    En el futuro, me gustaría expandir el proyecto agregando un blog donde los usuarios puedan comentar las imágenes.
                </p>
                <p>
                    Agradezco al profesor y tutores de Coder por su apoyo, ya que este proyecto representa un gran avance en mi camino como programador.
                </p>
            </div>
        </div>
    </div>
{% endblock content %}

proyecto/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="icon"
              type="image/x-icon"
              href=" {% static 'home/assets/favicon.ico' %} " />
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'home/componentes/navbar.html' %}
        <div class="container">
            <div class="text-center mt-5 pa">
                <h1>
                    {% block body_title %}
                    {% endblock body_title %}
                </h1>
                <p class="lead mb-2;">
                    {% block body_subtitle %}
                    {% endblock body_subtitle %}
                </p>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

proyecto/home/templates/home/componentes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:index' %}">Animalix , tu foro salvaje.</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active"
                       aria-current="page"
                       href="{% url 'home:index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'colaborador:imagen_list' %}">Galeria</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       id="navbarDropdown"
                       href="{% url 'colaborador:colaborador_list' %}"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">Colaboradores</a>
                    <ul class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'colaborador:colaborador_list' %}">Nuestros Colaboradores</a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'colaborador:colaborador_create' %}">Ser un colaborador</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

proyecto/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    Animalix | Inicio
{% endblock title %}
{% block body_title %}
    <h1 class="display-4 text-center mb-4">Bienvenido a Animalix!</h1>
{% endblock body_title %}
{% block body_subtitle %}
    <h2 class="text-center">
        Animalix es un foro en donde podrás compartir tus imágenes de animales salvajes con todo el mundo!
    </h2>
{% endblock body_subtitle %}
{% block content %}
    <div class="container">
        <ul class="list-group list-group-flush mt-4">
            <li class="list-group-item">
                <a href="{% url 'colaborador:imagen_list' %}" class="btn btn-primary">Galería de Imágenes</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'colaborador:colaborador_list' %}"
                   class="btn btn-secondary">Sobre nuestros Colaboradores</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'home:about' %}" class="btn btn-primary">Sobre el desarrollador</a>
            </li>
        </ul>
    </div>
{% endblock content %}

proyecto/home/templates/home/login.html
{% extends 'home/base.html' %}
{% block title %}
    Animalix | Logeo de usuario
{% endblock title %}
{% block body_title %}
    Login
{% endblock body_title %}
{% block content %}
    <div class="container">
        <form method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username:</label>
                <p class="form-control">{{ form.username }}</p>
            </div>
            <div class="form-group">
                <label for="id_password">Password:</label>
                <p class="form-control">{{ form.password }}</p>
            </div>
            <input type="hidden" name="next" value="{% url 'home:index' %}">
            <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
            <a href="{% url 'home:index' %}" class="btn btn-secondary">Volver a inicio</a>
        </form>
    </div>
{% endblock content %}

proyecto/home/templates/home/logout.html
{% extends 'home/base.html' %}
{% block title %}
    Animalix | Logout
{% endblock title %}
{% block body_title %}
    Logout
{% endblock body_title %}
{% block content %}
    <p class="fs-5 ">Has cerrado Sesion</p>
    <a href="{% url 'home:index' %}" class="btn btn-secondary ">Volver a inicio</a>
{% endblock content %}

proyecto/home/templates/home/register.html
{% extends 'home/base.html' %}
{% block title %}
    Animalix | Registro Colaborador
{% endblock title %}
{% block body_title %}
    Registro de Nuevo Colaborador
{% endblock body_title %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <input type="hidden" name="next" value="{% url 'home:login' %}">
        </table>
        <button type="submit" class="btn btn-primary ">Registrarse</button>
        <a href="{% url 'home:index' %}" class="btn btn-secondary ">Volver a inicio</a>
    </form>
{% endblock content %}